targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          generate_for:
            - lib/core/di/injection_container.dart
