import 'package:flutter/material.dart';
import 'story_prompt.dart';

/// Represents a pre-defined quick prompt for the carousel
class QuickPrompt {
  final String id;
  final String title;
  final String subtitle;
  final IconData icon;
  final StoryPrompt presetOptions;
  final List<Color> gradientColors;

  const QuickPrompt({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.presetOptions,
    required this.gradientColors,
  });

  /// Hardcoded list of quick prompts for the carousel
  static List<QuickPrompt> get defaultPrompts => [
    QuickPrompt(
      id: 'warrior_quest',
      title: "A Warrior's Quest",
      subtitle: 'Epic adventure from Mahabharata',
      icon: Icons.shield,
      gradientColors: [const Color(0xFF667eea), const Color(0xFF764ba2)],
      presetOptions: const StoryPrompt(
        scripture: 'Mahabharata',
        storyType: 'Epic Adventure',
        theme: 'Dharma (Duty)',
        mainCharacter: 'Warrior/Kshatriya',
        setting: 'Epic Battlefield',
      ),
    ),
    QuickPrompt(
      id: 'krishna_wisdom',
      title: "Krishna's Wisdom",
      subtitle: 'Divine teachings and philosophy',
      icon: Icons.auto_awesome,
      gradientColors: [const Color(0xFF11998e), const Color(0xFF38ef7d)],
      presetOptions: const StoryPrompt(
        scripture: 'Bhāgavata Purāṇa',
        storyType: 'Philosophical Journey',
        theme: 'Knowledge & Wisdom',
        mainCharacter: 'Divine Being',
        setting: 'Royal Palace',
      ),
    ),
    QuickPrompt(
      id: 'sage_journey',
      title: "A Sage's Journey",
      subtitle: 'Spiritual transformation story',
      icon: Icons.self_improvement,
      gradientColors: [const Color(0xFFf093fb), const Color(0xFFf5576c)],
      presetOptions: const StoryPrompt(
        scripture: 'Upanishads',
        storyType: 'Spiritual Transformation',
        theme: 'Moksha (Liberation)',
        mainCharacter: 'Sage/Rishi',
        setting: "Sage's Ashram",
      ),
    ),
    QuickPrompt(
      id: 'rama_devotion',
      title: "Path of Devotion",
      subtitle: 'Devotional tale from Ramayana',
      icon: Icons.favorite,
      gradientColors: [const Color(0xFFff9a9e), const Color(0xFFfecfef)],
      presetOptions: const StoryPrompt(
        scripture: 'Ramayana',
        storyType: 'Devotional Story',
        theme: 'Bhakti (Devotion)',
        mainCharacter: 'Devoted Seeker',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'animal_wisdom',
      title: "Tales of Wisdom",
      subtitle: 'Clever stories from Panchatantra',
      icon: Icons.pets,
      gradientColors: [const Color(0xFFa8edea), const Color(0xFFfed6e3)],
      presetOptions: const StoryPrompt(
        scripture: 'Panchatantra',
        storyType: 'Animal Fable',
        theme: 'Cleverness & Wit',
        mainCharacter: 'Talking Animal',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'divine_legend',
      title: "Divine Legend",
      subtitle: 'Cosmic tales of creation',
      icon: Icons.blur_on,
      gradientColors: [const Color(0xFF4facfe), const Color(0xFF00f2fe)],
      presetOptions: const StoryPrompt(
        scripture: 'Brahma Purāṇa',
        storyType: 'Creation Myth',
        theme: 'Cosmic Harmony',
        mainCharacter: 'Divine Being',
        setting: 'Celestial Realm',
      ),
    ),

    // --- New (16 more) ---
    QuickPrompt(
      id: 'arjuna_dharma',
      title: "Arjuna's Dharma",
      subtitle: 'A duty-bound turning point',
      icon: Icons.balance,
      gradientColors: [const Color(0xFF00c6ff), const Color(0xFF0072ff)],
      presetOptions: const StoryPrompt(
        scripture: 'Mahabharata',
        storyType: 'Philosophical Journey',
        theme: 'Dharma (Duty)',
        mainCharacter: 'Warrior/Kshatriya',
        setting: 'Epic Battlefield',
      ),
    ),
    QuickPrompt(
      id: 'gita_on_field',
      title: "Song on the Battlefield",
      subtitle: 'Wisdom spoken amidst conflict',
      icon: Icons.psychology,
      gradientColors: [const Color(0xFFf7971e), const Color(0xFFffd200)],
      presetOptions: const StoryPrompt(
        scripture: 'Mahabharata',
        storyType: 'Philosophical Journey',
        theme: 'Knowledge & Wisdom',
        mainCharacter: 'Divine Being',
        setting: 'Epic Battlefield',
      ),
    ),
    QuickPrompt(
      id: 'bheeshma_oath',
      title: "Bheeshma's Oath",
      subtitle: 'A vow that shapes a kingdom',
      icon: Icons.gavel,
      gradientColors: [const Color(0xFF232526), const Color(0xFF414345)],
      presetOptions: const StoryPrompt(
        scripture: 'Mahabharata',
        storyType: 'Epic Adventure',
        theme: 'Dharma (Duty)',
        mainCharacter: 'Warrior/Kshatriya',
        setting: 'Royal Palace',
      ),
    ),
    QuickPrompt(
      id: 'warrior_inner_shift',
      title: "The Warrior Within",
      subtitle: 'From struggle to liberation',
      icon: Icons.self_improvement,
      gradientColors: [const Color(0xFFDA4453), const Color(0xFF89216B)],
      presetOptions: const StoryPrompt(
        scripture: 'Mahabharata',
        storyType: 'Spiritual Transformation',
        theme: 'Moksha (Liberation)',
        mainCharacter: 'Warrior/Kshatriya',
        setting: 'Epic Battlefield',
      ),
    ),
    QuickPrompt(
      id: 'forest_devotion',
      title: "Forest of Devotion",
      subtitle: 'Faith tested in the wilds',
      icon: Icons.park,
      gradientColors: [const Color(0xFF56ab2f), const Color(0xFFa8e063)],
      presetOptions: const StoryPrompt(
        scripture: 'Ramayana',
        storyType: 'Devotional Story',
        theme: 'Bhakti (Devotion)',
        mainCharacter: 'Devoted Seeker',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'hanuman_valor',
      title: "Hanuman's Valor",
      subtitle: 'A leap of courage and faith',
      icon: Icons.flight_takeoff,
      gradientColors: [const Color(0xFF2193b0), const Color(0xFF6dd5ed)],
      presetOptions: const StoryPrompt(
        scripture: 'Ramayana',
        storyType: 'Epic Adventure',
        theme: 'Bhakti (Devotion)',
        mainCharacter: 'Devoted Seeker',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'sita_resolve',
      title: "Sita's Resolve",
      subtitle: 'Strength through inner freedom',
      icon: Icons.wb_sunny,
      gradientColors: [const Color(0xFFee0979), const Color(0xFFff6a00)],
      presetOptions: const StoryPrompt(
        scripture: 'Ramayana',
        storyType: 'Spiritual Transformation',
        theme: 'Moksha (Liberation)',
        mainCharacter: 'Devoted Seeker',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'rama_duty_path',
      title: "Rama's Duty",
      subtitle: 'Choosing dharma over comfort',
      icon: Icons.assistant_direction,
      gradientColors: [const Color(0xFF614385), const Color(0xFF516395)],
      presetOptions: const StoryPrompt(
        scripture: 'Ramayana',
        storyType: 'Epic Adventure',
        theme: 'Dharma (Duty)',
        mainCharacter: 'Warrior/Kshatriya',
        setting: 'Royal Palace',
      ),
    ),
    QuickPrompt(
      id: 'narada_lessons',
      title: "Narada's Lessons",
      subtitle: 'A sage guides kings and gods',
      icon: Icons.temple_hindu,
      gradientColors: [const Color(0xFF30cfd0), const Color(0xFF330867)],
      presetOptions: const StoryPrompt(
        scripture: 'Bhāgavata Purāṇa',
        storyType: 'Philosophical Journey',
        theme: 'Knowledge & Wisdom',
        mainCharacter: 'Sage/Rishi',
        setting: 'Celestial Realm',
      ),
    ),
    QuickPrompt(
      id: 'prahlada_faith',
      title: "Prahlada's Faith",
      subtitle: 'Devotion that cannot be broken',
      icon: Icons.favorite_border,
      gradientColors: [const Color(0xFFff512f), const Color(0xFFdd2476)],
      presetOptions: const StoryPrompt(
        scripture: 'Bhāgavata Purāṇa',
        storyType: 'Devotional Story',
        theme: 'Bhakti (Devotion)',
        mainCharacter: 'Devoted Seeker',
        setting: 'Royal Palace',
      ),
    ),
    QuickPrompt(
      id: 'divine_play_forest',
      title: "Divine Play",
      subtitle: 'Mystery and grace in the forest',
      icon: Icons.auto_awesome_motion,
      gradientColors: [const Color(0xFF8360c3), const Color(0xFF2ebf91)],
      presetOptions: const StoryPrompt(
        scripture: 'Bhāgavata Purāṇa',
        storyType: 'Devotional Story',
        theme: 'Bhakti (Devotion)',
        mainCharacter: 'Divine Being',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'upanishad_dialogue',
      title: "Upanishadic Dialogue",
      subtitle: 'Questions that open the self',
      icon: Icons.question_answer,
      gradientColors: [const Color(0xFF1f4037), const Color(0xFF99f2c8)],
      presetOptions: const StoryPrompt(
        scripture: 'Upanishads',
        storyType: 'Philosophical Journey',
        theme: 'Knowledge & Wisdom',
        mainCharacter: 'Sage/Rishi',
        setting: "Sage's Ashram",
      ),
    ),
    QuickPrompt(
      id: 'self_inquiry_ashram',
      title: "Self-Inquiry",
      subtitle: 'A path toward liberation',
      icon: Icons.travel_explore,
      gradientColors: [const Color(0xFF0f2027), const Color(0xFF2c5364)],
      presetOptions: const StoryPrompt(
        scripture: 'Upanishads',
        storyType: 'Spiritual Transformation',
        theme: 'Moksha (Liberation)',
        mainCharacter: 'Devoted Seeker',
        setting: "Sage's Ashram",
      ),
    ),
    QuickPrompt(
      id: 'panchatantra_court',
      title: "Court of Beasts",
      subtitle: 'Wit and strategy in a royal court',
      icon: Icons.account_balance,
      gradientColors: [const Color(0xFFf46b45), const Color(0xFFeea849)],
      presetOptions: const StoryPrompt(
        scripture: 'Panchatantra',
        storyType: 'Animal Fable',
        theme: 'Cleverness & Wit',
        mainCharacter: 'Talking Animal',
        setting: 'Royal Palace',
      ),
    ),
    QuickPrompt(
      id: 'forest_trickster',
      title: "Forest Trickster",
      subtitle: 'A clever animal outsmarts danger',
      icon: Icons.emoji_nature,
      gradientColors: [const Color(0xFF43cea2), const Color(0xFF185a9d)],
      presetOptions: const StoryPrompt(
        scripture: 'Panchatantra',
        storyType: 'Animal Fable',
        theme: 'Cleverness & Wit',
        mainCharacter: 'Talking Animal',
        setting: 'Sacred Forest',
      ),
    ),
    QuickPrompt(
      id: 'cosmic_order',
      title: "Cosmic Order",
      subtitle: 'Harmony written into creation',
      icon: Icons.public,
      gradientColors: [const Color(0xFF3a7bd5), const Color(0xFF3a6073)],
      presetOptions: const StoryPrompt(
        scripture: 'Brahma Purāṇa',
        storyType: 'Creation Myth',
        theme: 'Cosmic Harmony',
        mainCharacter: 'Divine Being',
        setting: 'Celestial Realm',
      ),
    ),
    QuickPrompt(
      id: 'rishi_of_cosmos',
      title: "Rishi of the Cosmos",
      subtitle: 'A sage witnesses the universe unfold',
      icon: Icons.hub,
      gradientColors: [const Color(0xFF41295a), const Color(0xFF2F0743)],
      presetOptions: const StoryPrompt(
        scripture: 'Brahma Purāṇa',
        storyType: 'Philosophical Journey',
        theme: 'Cosmic Harmony',
        mainCharacter: 'Sage/Rishi',
        setting: 'Celestial Realm',
      ),
    ),
  ];
}
