// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:myitihas/features/chat/data/models/conversation_model.dart';
import 'package:myitihas/features/chat/data/models/message_model.dart';
import 'package:myitihas/features/chat/domain/entities/message.dart';
import 'package:myitihas/features/home/data/models/activity_item_model.dart';
import 'package:myitihas/features/notifications/data/models/notification_model.dart';
import 'package:myitihas/features/notifications/domain/entities/notification.dart';
import 'package:myitihas/features/social/data/models/comment_model.dart';
import 'package:myitihas/features/social/data/models/like_model.dart';
import 'package:myitihas/features/social/data/models/share_model.dart';
import 'package:myitihas/features/social/data/models/user_model.dart';
import 'package:myitihas/features/social/domain/entities/share.dart';
import 'package:myitihas/features/stories/data/models/story_model.dart';
import 'package:myitihas/services/reading_progress_service.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityItemModelAdapter());
    registerAdapter(CommentModelAdapter());
    registerAdapter(ConversationModelAdapter());
    registerAdapter(LikeModelAdapter());
    registerAdapter(MessageDeliveryStatusAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(ReadingProgressAdapter());
    registerAdapter(ShareModelAdapter());
    registerAdapter(ShareTypeAdapter());
    registerAdapter(StoryAttributesModelAdapter());
    registerAdapter(StoryModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityItemModelAdapter());
    registerAdapter(CommentModelAdapter());
    registerAdapter(ConversationModelAdapter());
    registerAdapter(LikeModelAdapter());
    registerAdapter(MessageDeliveryStatusAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(ReadingProgressAdapter());
    registerAdapter(ShareModelAdapter());
    registerAdapter(ShareTypeAdapter());
    registerAdapter(StoryAttributesModelAdapter());
    registerAdapter(StoryModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
